[package]
name = "pokerust"
version = "0.0.0"
edition = "2021"
authors = ["geckronome"]
repository = "https://github.com/geckro/pokerust"
license = "MIT"

[dependencies]
rand = "0.8.5"
toml = "0.8.2"
